// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IWyTwr5Xk3U9XAC2dAVQWvloCkT_uAg',
    appId: '1:766645636867:web:b005b7facf2a9c114fe336',
    messagingSenderId: '766645636867',
    projectId: 'app-warehouse-55797',
    authDomain: 'app-warehouse-55797.firebaseapp.com',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxlc2PWN92qI9L015_xB_hSCj3ye9fa8',
    appId: '1:766645636867:android:78d41acbf58cfc324fe336',
    messagingSenderId: '766645636867',
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfS2JgSxfyAOoBREj6AUxtu82MrgkRZ70',
    appId: '1:766645636867:ios:4cfa177bafc8a9cd4fe336',
    messagingSenderId: '766645636867',
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfS2JgSxfyAOoBREj6AUxtu82MrgkRZ70',
    appId: '1:766645636867:ios:4cfa177bafc8a9cd4fe336',
    messagingSenderId: '766645636867',
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4IWyTwr5Xk3U9XAC2dAVQWvloCkT_uAg',
    appId: '1:766645636867:web:b005b7facf2a9c114fe336',
    messagingSenderId: '766645636867',
    projectId: 'app-warehouse-55797',
    authDomain: 'app-warehouse-55797.firebaseapp.com',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

}