// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'secrets.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseApiKey1,
    appId: '1:877113087703:web:732decb046856c25ae8292',
    messagingSenderId: '877113087703',
    projectId: 'flutter-test-9a276',
    authDomain: 'flutter-test-9a276.firebaseapp.com',
    storageBucket: 'flutter-test-9a276.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseApiKey2,
    appId: '1:877113087703:android:beca8092e98309feae8292',
    messagingSenderId: '877113087703',
    projectId: 'flutter-test-9a276',
    storageBucket: 'flutter-test-9a276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseApiKey3,
    appId: '1:877113087703:ios:4eed052eae5602d3ae8292',
    messagingSenderId: '877113087703',
    projectId: 'flutter-test-9a276',
    storageBucket: 'flutter-test-9a276.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: firebaseApiKey3,
    appId: '1:877113087703:ios:4eed052eae5602d3ae8292',
    messagingSenderId: '877113087703',
    projectId: 'flutter-test-9a276',
    storageBucket: 'flutter-test-9a276.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: firebaseApiKey1,
    appId: '1:877113087703:web:4afae0fe3297e642ae8292',
    messagingSenderId: '877113087703',
    projectId: 'flutter-test-9a276',
    authDomain: 'flutter-test-9a276.firebaseapp.com',
    storageBucket: 'flutter-test-9a276.firebasestorage.app',
  );
}
